rules = [
  ExplicitResultTypes,
  OrganizeImports,
  DisableSyntax,
  ExplicitResultTypes,
  LeakingImplicitClassVal,
  NoAutoTupling,
  NoValInForComprehension,
  RedundantSyntax,
  RemoveUnused,
  ProcedureSyntax
]

OrganizeImports {
  groups = [
    "re:javax?\\."
    "scala."
    "sbt."
    "*"
  ]
  targetDialect = Scala3
  removeUnused = true
}
